### ISSUE TITLE
map not show after saving

### ISSUE THREAD

**Issue by sashagar** [intelliants/subrion-plugin-gmap#10]
Install templates cars or autosales

Go to profile page. Maps will shown

Press on `Save` button . Map won't shown

Refresh page. Map will shown

**Comment by ghost** [comment]
Confirmed.

**Comment by ghost** [comment]
Fixed in the script core: https://github.com/intelliants/subrion/commit/a20686cc821cb6ad1c50e209d8163d54d4790f9c
