### ISSUE TITLE
Not working block "lisings on map" at Yellowpages

### ISSUE THREAD

**Issue by amalychev** [intelliants/subrion-plugin-gmap#4]
Venues are not displayed in block Listings on map

**Comment by agorshechnikov** [comment]
Issue doesn't exist in the latest version (4.0.3) of Gmap plugin.
Venues must have values in lat & lng columns in order to be displayed in the **Listings on map block**.
![image](https://cloud.githubusercontent.com/assets/15151937/21498418/0fc52b0c-cc4e-11e6-8baa-5b66b5d73115.jpg)
